**NumPy is a place where you can store your data**
*It is base library for all data science tools*


1.   Performance - faster operations
2.   Convenience for maths operations

Multi dimensional data representation,
Large Collection of built-in functions,
Vectorization - avoid loops,
Support for large data sets,
Integration with other libraries,
Type safety - all elements in one datatype,
Memory efficiency

In [4]:
import numpy

**Creating numpy array using single dimensional list**

In [6]:
lst=[9,26,13,1,30,45,5,11,75,25]
print(type(lst))
print(lst)
arr=numpy.array(lst)
print(type(arr))
print(arr)

<class 'list'>
[9, 26, 13, 1, 30, 45, 5, 11, 75, 25]
<class 'numpy.ndarray'>
[ 9 26 13  1 30 45  5 11 75 25]


**Creating numpy array from a double dimensional list**

In [8]:
lst=[
    [12,23,34,66],
    [65,43,21,33],
    [76,89,58,22]
]
print(lst)
arr=numpy.array(lst)
print(arr)

[[12, 23, 34, 66], [65, 43, 21, 33], [76, 89, 58, 22]]
[[12 23 34 66]
 [65 43 21 33]
 [76 89 58 22]]


In [9]:
res=arr+3
print(res)

[[15 26 37 69]
 [68 46 24 36]
 [79 92 61 25]]


In [10]:
sqr=arr**2
print(sqr)

[[ 144  529 1156 4356]
 [4225 1849  441 1089]
 [5776 7921 3364  484]]


**Creating numpy array from range of values**

In [13]:
arr=numpy.arange(45,60)
print(arr)
arr=numpy.arange(1,25,3)
print(arr)
arr=numpy.arange(75,50,-4)
print(arr)

[45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 1  4  7 10 13 16 19 22]
[75 71 67 63 59 55 51]


**Creating numpy array from Linear spacing**

In [14]:
arr=numpy.linspace(1,13,9)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]


**Numpy arrays with zeros and ones**

In [16]:
arr0=numpy.zeros((4,6))
print(arr0)
arr1=numpy.ones((5,8))
print(arr1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
