**Creating numpy from random numbers**

In [1]:
import numpy

In [2]:
arr=numpy.random.random(10)
print(arr)

[0.04250323 0.77169028 0.15306915 0.1405695  0.74984146 0.84541553
 0.56834695 0.75440165 0.08955064 0.48516509]


In [3]:
arr=numpy.random.random((3,5))
print(arr)

[[0.8387473  0.68555522 0.91538773 0.68380916 0.44434536]
 [0.23703337 0.49310267 0.62097045 0.55876079 0.70332442]
 [0.18292953 0.59240569 0.94932194 0.3085701  0.23873592]]


In [16]:
arr=numpy.random.randint(15)
print(arr)

4


In [20]:
arr=numpy.random.randint(1,45,10)
print(arr)

[37 15 10 25 29 16 25  9 33 13]


In [18]:
x=numpy.random.choice(arr)
print(x)

17


In [22]:
arr=numpy.random.randint(1,45,(3,4))
print(arr)

[[36 10 27 35]
 [20  4 12 24]
 [43 43  9  6]]


In [23]:
print(arr.dtype)

int64


**numpy array of other data types**

In [24]:
arrs=numpy.array(['praffull','java','python','sql','spark','microsoft','volkswagen'])
print(arrs)

['praffull' 'java' 'python' 'sql' 'spark' 'microsoft' 'volkswagen']


In [25]:
print(arrs.dtype)

<U10


In [27]:
arrd=numpy.arange('2024-12-01','2025-01-05',dtype='datetime64[D]')
print(arrd)

['2024-12-01' '2024-12-02' '2024-12-03' '2024-12-04' '2024-12-05'
 '2024-12-06' '2024-12-07' '2024-12-08' '2024-12-09' '2024-12-10'
 '2024-12-11' '2024-12-12' '2024-12-13' '2024-12-14' '2024-12-15'
 '2024-12-16' '2024-12-17' '2024-12-18' '2024-12-19' '2024-12-20'
 '2024-12-21' '2024-12-22' '2024-12-23' '2024-12-24' '2024-12-25'
 '2024-12-26' '2024-12-27' '2024-12-28' '2024-12-29' '2024-12-30'
 '2024-12-31' '2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04']


In [28]:
print(arrd.dtype)

datetime64[D]


In [33]:
arrb=numpy.array([True,True,False,True,False,False,False,True])
print(arrb)

[ True  True False  True False False False  True]


In [34]:
print(arrb.dtype)

bool


**Single datatype in numpy**

In [35]:
arrm=numpy.array(['praffull',9,26.13,True])
print(arrm)
print(arrm.dtype)

['praffull' '9' '26.13' 'True']
<U32
