In [2]:
import numpy

In [3]:
arr1=numpy.array([[12,23],[45,56],[78,89]])
print(arr1)
arr1+=5
print(arr1)

[[12 23]
 [45 56]
 [78 89]]
[[17 28]
 [50 61]
 [83 94]]


In [4]:
arr2=numpy.array([[2,3],[4,5],[2,4]])
print(arr2)

[[2 3]
 [4 5]
 [2 4]]


In [5]:
print(arr1+arr2)

[[19 31]
 [54 66]
 [85 98]]


In [6]:
print(arr1*arr2)

[[ 34  84]
 [200 305]
 [166 376]]


In [7]:
arr=numpy.array([1,2,3,4,5])

In [8]:
print(numpy.sum(arr))

15


In [9]:
print(numpy.prod(arr))

120


In [12]:
print(numpy.add(arr1,arr2))
#substract, multiply, divide, mod

[[19 31]
 [54 66]
 [85 98]]


In [14]:
print(numpy.power(arr1,arr2))
print(numpy.sqrt(arr1))
print(numpy.square(arr2))

[[      289     21952]
 [  6250000 844596301]
 [     6889  78074896]]
[[4.12310563 5.29150262]
 [7.07106781 7.81024968]
 [9.11043358 9.69535971]]
[[ 4  9]
 [16 25]
 [ 4 16]]
