In [1]:
import numpy

In [2]:
a1=numpy.array([34,78,52])
a2=numpy.array([12,34,56,78,90,31])

In [3]:
res=numpy.concatenate((a1,a2))
print(res)

[34 78 52 12 34 56 78 90 31]


In [4]:
a3=numpy.array([[1,2,3],[4,5,6]])
a4=numpy.array([[8,7,1],[6,2,9],[1,5,3]])
print(a3)
print(a4)

[[1 2 3]
 [4 5 6]]
[[8 7 1]
 [6 2 9]
 [1 5 3]]


In [5]:
res=numpy.concatenate((a3,a4))
print(res)

[[1 2 3]
 [4 5 6]
 [8 7 1]
 [6 2 9]
 [1 5 3]]


In [6]:
a5=numpy.array([[1,2,3],[4,5,6]])
a6=numpy.array([[7,9],[4,6]])
print(a5)
print(a6)

[[1 2 3]
 [4 5 6]]
[[7 9]
 [4 6]]


In [8]:
res=numpy.concatenate((a5,a6),axis=1)
print(res)

[[1 2 3 7 9]
 [4 5 6 4 6]]
