In [1]:
import numpy

In [4]:
a1=numpy.array([[1,2,3],[4,5,6]])
a2=numpy.array([[9,2,5],[3,5,6]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[9 2 5]
 [3 5 6]]


In [5]:
comp=(a1==a2)
print(comp)

[[False  True False]
 [False  True  True]]


In [7]:
print(comp.all())

False


In [8]:
if comp.all():
  print('both numpy arrays are exactly same')
else:
  print('numpy arrays are different')

numpy arrays are different
