**Subset from 1-D NumPy array**

In [1]:
import numpy

In [2]:
arr=numpy.array([12,23,34,45,56,67,78,89,90])

In [3]:
print(arr)

[12 23 34 45 56 67 78 89 90]


In [4]:
print(arr[5])

67


In [5]:
print(arr[2:7])

[34 45 56 67 78]


In [6]:
print(arr[3:])
print(arr[:5])
print(arr[-1])

[45 56 67 78 89 90]
[12 23 34 45 56]
90


In [8]:
print(arr[arr%2==1])
print(arr[arr>50])

[23 45 67 89]
[56 67 78 89 90]


**Subset from 2-D numpy arrays**

In [9]:
arr=numpy.array([
    [34,78,22,12,54],
    [60,16,41,38,99],
    [21,55,82,51,94]
])
print(arr)

[[34 78 22 12 54]
 [60 16 41 38 99]
 [21 55 82 51 94]]


In [11]:
#all rows all columns
print(arr)
print(arr[:,:])

[[34 78 22 12 54]
 [60 16 41 38 99]
 [21 55 82 51 94]]
[[34 78 22 12 54]
 [60 16 41 38 99]
 [21 55 82 51 94]]


In [12]:
print(arr[:,0:3])

[[34 78 22]
 [60 16 41]
 [21 55 82]]


In [13]:
print(arr[1,2])

41


In [14]:
print(arr[1:,2:])

[[41 38 99]
 [82 51 94]]


In [15]:
print(arr[2,:])

[21 55 82 51 94]


In [17]:
print(arr[arr%2==1])
print(arr[arr<50])

[41 99 21 55 51]
[34 22 12 16 41 38 21]
